// Auto-generated by VIP Connect Bot — do not edit manually
// To update, post changes in the event's Slack channel

export const eventConfig = {
  "city": "London",
  "venue": "Stafford hotel Wine Cellar, 16 St James's Pl, London SW1A 1NJ",
  "capacity": 40,
  "eventTitle": "VIP Connect — London Leadership Dinner",
  "heroImageUrl": "https://zxjuq10yjr13vx51.public.blob.vercel-storage.com/photos/moloco-event-london/the-stafford-wine-cellar-1-1400x590-1-e1558082926675.jpg",
  "heroHeadline": "VIP Connect",
  "heroSubheadline": "London Leadership Dinner",
  "heroDescription": "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",
  "experienceHeadline": "Forty leaders. An 18th-century wine cellar beneath St James's. No slides.",
  "experienceParagraphs": [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other's assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What's working, what's not, and what the next twelve months look like.",
    "We gather in the atmospheric wine cellar of The Stafford, where historic stone vaults create the perfect setting for fintech leadership dialogue."
  ],
  "agendaItems": [
    {
      "time": "5:00 PM",
      "title": "Arrival & Welcome Drinks",
      "description": "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small."
    },
    {
      "time": "5:30 PM",
      "title": "Executive Session",
      "description": "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like."
    },
    {
      "time": "5:45 PM",
      "title": "Dinner",
      "description": "An evening of strategic discussion on AI's transformation of financial services marketing, exploring revenue alignment and privacy navigation."
    },
    {
      "time": "8:00 PM",
      "title": "Event Close",
      "description": "An informal close as the evening winds down."
    }
  ],
  "agendaShort": [
    {
      "time": "5:00 PM",
      "label": "Arrival & welcome drinks"
    },
    {
      "time": "5:30 PM",
      "label": "Executive session"
    },
    {
      "time": "5:45 PM",
      "label": "Dinner"
    },
    {
      "time": "8:00 PM",
      "label": "Event close"
    }
  ],
  "faqItems": [
    {
      "q": "What is Moloco VIP Connect?",
      "a": "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion."
    },
    {
      "q": "Who is this event for?",
      "a": "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 40 people. Small enough that everyone speaks, diverse enough that you'll hear something that changes how you think about a problem."
    },
    {
      "q": "Is this a public event / can I bring a +1?",
      "a": "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link."
    },
    {
      "q": "What should I wear?",
      "a": "Smart casual. Polished but comfortable. Think what you'd wear to dinner with people you want to impress without looking like you tried."
    },
    {
      "q": "Is there a cost to attend?",
      "a": "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco."
    },
    {
      "q": "What about dietary requirements?",
      "a": "Stafford hotel Wine Cellar, 16 St James's Pl, London SW1A 1NJ accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they'll take care of it."
    }
  ],
  "calendarTitle": "Moloco VIP Connect — London Leadership Dinner",
  "calendarUidPrefix": "moloco-vip-connect-2026",
  "siteUrl": "https://moloco-event-london.vercel.app",
  "slug": "moloco-event-london",
  "eventSubtitle": "An intimate fintech leadership dinner exploring AI's impact on financial services marketing",
  "venueAddress": "16 St James's Place, SW1A 1NJ, London",
  "venueAddressFull": "16 St James's Place, London SW1A 1NJ, United Kingdom",
  "date": "May 14, 2024",
  "dateFull": "Tuesday, May 14",
  "dateISO": "2024-05-14",
  "calendarDateStart": "20240514T170000",
  "calendarDateEnd": "20240514T200000",
  "time": "5:00 PM",
  "timezone": "Europe/London",
  "timezoneAbbr": "BST",
  "venueDescription": "The Stafford's historic wine cellar occupies centuries-old vaults beneath one of London's finest boutique hotels. Stone archways and candlelit alcoves create an atmosphere of refined intimacy, while the collection of rare vintages provides a sophisticated backdrop for executive conversation.",
  "venueCapacityNote": "The private dining space accommodates forty guests across intimate round tables within the atmospheric cellar setting.",
  "venueDiningNote": "Contemporary British cuisine paired with selections from the hotel's exceptional wine collection.",
  "venueDirections": "The Stafford is located on St James's Place, just off St James's Street. Green Park Underground station is a three-minute walk. Enter through the hotel's main entrance and reception will direct you to the wine cellar.",
  "venueExperienceLine": "We gather in the atmospheric wine cellar of The Stafford, where historic stone vaults create the perfect setting for fintech leadership dialogue.",
  "dinnerDescription": "An evening of strategic discussion on AI's transformation of financial services marketing, exploring revenue alignment and privacy navigation.",
  "mapsUrl": "https://www.google.com/maps/place/The+Stafford+London/@51.5055,-0.1416,17z"
};